name: learn-github-actions
on:
  schedule:
    - cron:  '*/1 * * * *' #1分に1回実行

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: echo "This step will always run"
